export const EVENT_LIST = {
    CHANNEL_EXECUTE: "CHANNEL_EXECUTE",
    CHANNEL_CREATE: "CHANNEL_CREATE",
    CHANNEL_HANGUP_COMPLETE: "CHANNEL_HANGUP_COMPLETE",
    CHANNEL_HANGUP: "CHANNEL_HANGUP",
    EVENT_NAME: "EVENT-NAME",
    CHANNEL_EXECUTE_COMPLETE: "CHANNEL_EXECUTE_COMPLETE"
};